version: '3'

services:
  scraper:
    build: .
    volumes:
      - ./:/app
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    command: ["--method", "all"]
    # If you want to use proxy, uncomment and modify the line below
    # command: 